# Generated by Django 2.2.5 on 2019-09-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underlords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='alliances',
            field=models.ManyToManyField(to='underlords.Alliances'),
        ),
        migrations.DeleteModel(
            name='HeroesAlliances',
        ),
    ]
